/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tyler_failed;

public class App {
    public String getGreeting() {
        return "tyler failed";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
